POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "name":"Sumit Rawat",
    "email":"sumit@gmail.com",
    "password":"123456"
  
}

###

POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email":"sumit@gmail.com",
    "password":"123456"
}

###
GET http://localhost:3000/protected
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiU3VtaXQgUmF3YXQiLCJlbWFpbCI6InN1bWl0QGdtYWlsLmNvbSIsImlkIjoiNjYxY2U5YTZmMWQzYWU5NGFlOTdhYTRjIiwiaWF0IjoxNzEzMTcwODU2fQ.wdYc3jxCLhSmp2EpDaiPQg1pfSK90_UNYVjji0huJMg


###

POST http://localhost:3000/url/create-short-url
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiU3VtaXQgUmF3YXQiLCJlbWFpbCI6InN1bWl0QGdtYWlsLmNvbSIsImlkIjoiNjYxY2U5YTZmMWQzYWU5NGFlOTdhYTRjIiwiaWF0IjoxNzEzMTcwODU2fQ.wdYc3jxCLhSmp2EpDaiPQg1pfSK90_UNYVjji0huJMg
Content-Type: application/json

{"url":"https://chat.openai.com/c/75bec158-5326-4458-ad47-fa031eb8c6d4"}